- Assets/Dev/Dev_Branchs/stage/Dev_Kasahara.unity
- Assets/Dev/Dev_Branchs/stage/GenarateObjectAlongGrid.cs
- Assets/Dev/Dev_Branchs/stage/Wall.prefab
オブジェクトを置ける条件の追加。2段以上は置けない。下に床がないと置けない。<-いくら
> Stageにオブジェクトを置く処理

- Assets/Dev/Dev_Branchs/particle/ClickDetection.cs
- Assets/Dev/Dev_Branchs/particle/ClickDetection.cs.meta
- Assets/Dev/Dev_Branchs/particle/ClickEffectVFX.vfx
- Assets/Dev/Dev_Branchs/particle/ClickEffectVFX.vfx.meta
- Assets/Dev/Dev_Branchs/particle/ParticleTestScene.unity
- Assets/Dev/Dev_Branchs/particle/ParticleTestScene.unity.meta
- Assets/Dev/Dev_Branchs/particle/UIEffectsPrefab.prefab
- Assets/Dev/Dev_Branchs/particle/UIEffectsPrefab.prefab.meta
- Packages/manifest.json
- Packages/packages-lock.json
- ProjectSettings/VFXManager.asset
Prefab設置後、MainCameraのStackにUICameraを追加して使います。
> [add] VFXGraphアセットの追加。クリック時のエフェクトプレファブを追加。

- Assets/Master/Script/InGame/Tallet/DefenseEquipmentManager_S/TrapTurretManager.cs
> [fix]存在しないデータを参照していたところの修正

- Assets/Dev/Dev_Branchs/stage/Master_Ingame_Stage(Copy).unity
- Assets/Dev/Dev_Branchs/stage/StageManager.cs
グリッドのサイズより小さいあたり判定のオブジェクトを除いて、同じ場所に重複してオブジェク…トを置けなくなりました。
> [Update]オブジェクトを設置する処理の改善。

- Assets/Dev/Dev_Branchs/stage/StageManager.cs
NavMeshSurfaceをGetComponentInChildrenで内部的に取得。
WallParentをスクリプトの初期化で生成。
FloorCenterを自動で算出。
> Issuesのいくつかを修正しました。

- Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
> [Fix]生成位置のずれに関する問題の修正(仮)

- Assets/Master/Resources/Prefab/InGame/Enemy/BossEnemy.prefab
- Assets/Master/Resources/Prefab/InGame/Enemy/Defenseenemy.prefab
- Assets/Master/Resources/Prefab/InGame/Enemy/FlyEnemy.prefab
- Assets/Master/Resources/Prefab/InGame/Enemy/NormalEnemy.prefab
- Assets/Master/Resources/Prefab/InGame/Enemy/PatrolEnemy.prefab
- Assets/Master/Resources/Prefab/InGame/Enemy/SpeedEnemy.prefab
- Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs
既に足の速さは変えるメソッドがあったので防御力のとこだけ書きました
> [Add]状態異常(防御力アップダウンの追加)、デバフ倍率とバフ倍率のプロパティ化(今後のため)

- Assets/Dev/Dev_Branchs/stage/Dev_Kobayashi/Master_Ingame_Stage0.unity
- Assets/Dev/Dev_Branchs/stage/Dev_Kobayashi/WaveData.asset
- Assets/Master/Script/InGame/Enemy/WaveData.cs
- Assets/Master/Script/InGame/Enemy/WaveManager.cs
クラスとデータを作成しました。
EnemyGeneratorに変更してもらう必要があるため、作成途中ではありますがプルリクします。
> [add]ウェーブシステムの追加

- Assets/Dev/Dev_Branchs/stage/StageManager.cs
> [fix]GroundのScaleが奇数の時(0,0,0)に置いても設置がずれないよう修正

- Assets/Dev/Dev_Branchs/stage/MuddySwamp.prefab
- Assets/Dev/Dev_Branchs/stage/PoisonousSwamp.prefab
- Assets/Dev/Dev_Branchs/stage/StageManager.cs
沼のプレハブの高さを低くする調整。
防衛設備を地面に直接設置する時に壁が同時に生成されるようにした。
> ステージ関係のアップデート

- Assets/Dev/Dev_Branchs/stage/ObstacleWall.prefab
- Assets/Dev/Dev_Branchs/stage/StageManager.cs
- Assets/Master/Scenes/Master_Scene/IngameScene/Master_Ingame_Stage0.unity
WallのレイヤーをBuildingsに変更して、StageManagerがレイヤーの変更に対応するようにしました
> [Update]WallのレイヤーをBuildingsに変更して、StageManagerがレイヤーの変更に対応するようにしました

- Assets/Master/Resources/Materials/GroundMaterial.mat
- Assets/Master/Scenes/Master_Scene/IngameScene/Master_Ingame_Stage1.unity
@kobakoGlhf
[[update]ステージのバグ、エラー修正、地面のshaderの切り替え、地面のstaticのBatching Staticを無効化](https://github.com/HIBIKI5201/Dungeon-Crafter/pull/199/commits/be0c143e98422e4de8f57812fa1a9898c69b1967)
> [update]ステージのバグ、エラー修正、地面のshaderの切り替え、地面のstaticのBatching Staticを無効化

- Assets/Master/Script/InGame/Stage/StageManager.cs
指定した座標上のタレットや壁をすべて消すようにした。
結構前に同じ機能を作ってたっぽいけど、対応と使い分けなどは後で考える。(てへっ♡忘れてた)
前作ったほうは無駄そうな処理があったので、新しいほうを採用すること。
動作確認済
> [update]StageManagerに置いたオブジェクトを消す処理の追加

- Assets/Master/Scenes/Master_Scene/IngameScene/Master_Ingame_Stage1.unity
> [fix]エネミーが出なくなっていたので修正

- Assets/Master/Script/InGame/Stage/StageManager.cs
成田君の要望でCheckObjectPlacedで得られる戻り値を逆に、ステージのGroundの中心から端までの距離を返すメソッドの追加。
それから右クリックによる壁の即時削除の無効化
> SatgeManagerにて、成田君に必要な処理の追加と、右クリックによる壁の即時削除の無効化

- Assets/Master/Scenes/Master_Scene/IngameScene/Master_Ingame_Stage0.unity
> [update]Stage0の地面の修正

- Assets/Master/Resources/ScriptableObject/PhaseData/TestData.asset
- Assets/Master/Resources/ScriptableObject/PhaseData/TestData.asset.meta
- Assets/Master/Script/InGame/Enemy/EnemyGenerator.cs
- Assets/Master/Script/InGame/Enemy/PhaseData.cs
- Assets/Master/Script/InGame/Enemy/WaveManager.cs
- Assets/Master/Script/InGame/PlayerManager.cs
ウェーブを選択肢の中からランダムに選択するように変更
ウェーブ終了時に敵のレベルがLoop回数上昇するように
フェーズデータの修正
> [update]ウェーブのランダム化とエンドレス化

- Assets/Master/Script/InGame/Stage/StageManager.cs
つつみんにUIを表示する処理をStageManagerのOnActivateTurretSelectedUIに登録するよう伝える必要あり。
> [update]タレットがクリックされたことをUIに通知する処理の追加。

- Assets/Master/Script/InGame/Tallet/DefenseEquipmentManager_B.cs
> [fix]プロパティつくりました

- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/AreaTurret.asset
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/AreaTurret.asset.meta
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/LongShootTurretDataBase.asset
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/ReinforceTurret.asset
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/ReinforceTurret.asset.meta
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/SlowTurretDataBase.asset
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/SlowTurretDataBase.asset.meta
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/SummonTurretDataBase.asset
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/TrapTurrerDataBase.asset
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/WeeknessTurretDataBase.asset
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/WeeknessTurretDataBase.asset.meta
- Assets/Master/Script/InGame/PlayerManager.cs
- Assets/Master/Script/InGame/Tallet/DefenseEquipmentDataBase.cs
UI及びStageが必要とするデータを取得できるように変更しました
一時的にガチャの処理を削除
> [update]UI及びStageが必要とするデータを取得できるように変更

- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/AreaTurret.asset
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/DefebseEquipmentDataBase.asset
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/LongShootTurretDataBase.asset
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/ReinforceTurret.asset
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/ShootTurretDataBase.asset
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/SlowTurretDataBase.asset
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/SummonTurretDataBase.asset
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/TrapTurrerDataBase.asset
- Assets/Master/Resources/ScriptableObject/DefenseEquipmentData/DataBase/WeeknessTurretDataBase.asset
- Assets/Master/Script/InGame/Enemy/PhaseManager.cs
- Assets/Master/Script/InGame/PlayerManager.cs
> Player manager

- Assets/Master/Script/System/Main/SaveDataManager.cs
> [update]ランキングをセーブできるようにした

- Assets/Master/Script/InGame/Stage/StageManager.cs
InGameUIManagerからStageManagerにマウスがUI乗ったことを検知したことを受け渡すことを確認
> [update]UI上にマウスカーソルがあるときタレットを置けないように更新

- Assets/Master/Script/InGame/PlayerManager.cs
> [update] タレットの削除処理を変更

- Assets/Master/Script/InGame/Stage/StageManager.cs
> [fix]インベントリからタレットを選択した後、タレットを設置せずにインベントリからタレットを選択した時にタレットが消えるバグの修正

- Assets/Master/Scenes/Master_Scene/IngameScene/Master_Ingame_Stage1.unity
- Assets/Master/Scenes/Master_Scene/IngameScene/Master_Ingame_Stage1/NavMesh-Ground 1.asset.meta
> [update]エネミーが正常に動かない問題の修正

- Assets/Master/Script/InGame/Enemy/PhaseManager.cs
インゲームのBGMが休憩中とそれ以外で変化するようになりました。
> [update]インゲームのBGMを変化するように

- Assets/Master/Script/InGame/PlayerManager.cs
> [update]InventoryのPowerUpRequireItemを削除

- Assets/Master/Script/InGame/Stage/StageManager.cs
> [update]タレット生成時にタレットを180度回転させて正面を向かせる

- Assets/Master/Resources/ScriptableObject/EnemyData/EnemyData.asset
- Assets/Master/Resources/ScriptableObject/PhaseData/TestData.asset
- Assets/Master/Script/System/Main/FrameWork.cs
> インゲーム終了後にエラーが出るスクリプトの箇所にトライキャッチした

- Assets/Master/Script/System/Main/AudioManager.cs
> [update]BGMが変更されない問題を修正

- Assets/Master/Materials/Ground.mat
- Assets/Master/Materials/Ground.mat.meta
- Assets/Master/Scenes/Master_Scene/IngameScene/Master_Ingame_Stage1.unity
> [fix]地面の変更

- Assets/Master/Script/InGame/Stage/StageManager.cs
タレットを選択してない時、hitに何も値が入らずnullになることが原因で強化パネルが出ませんでした
> [fix]タレットを選択できない問題を修正
